/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Alterar;

import Visao.Cadastrar.*;
import DAO.AdministradorDAO;
import DAO.Conexao;
import DAO.FuncionarioDAO;
import Modelo.Administrador;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Euxz
 */
public class AlterarAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarFuncionario
     */
    public AlterarAdministrador() {
        initComponents();
        setSize(975, 575);
    }

    private void InserirDados(int cod){
        
        Connection con = Conexao.AbrirConexao();
        AdministradorDAO sql = new AdministradorDAO(con);
        List<Administrador> lista = new ArrayList<>();
        lista = sql.CapturarAdministrador(cod);
        
        for(Administrador a : lista){
            codigo.setText(""+ a.getCod());
            jTF_nome.setText(a.getNome());
            jTF_usuario.setText(a.getUsuario());
            jTF_senha.setText(a.getSenha());
            jTF_senhaextra.setText(a.getSenhaextra());
        }
        Conexao.FecharConexao(con);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTF_nome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTF_usuario = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTF_cod = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTF_senha = new javax.swing.JTextField();
        jTF_senhaextra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 230, 80, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 350, 82, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Senha Extra:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 420, 153, 20);

        jTF_nome.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTF_nome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        getContentPane().add(jTF_nome);
        jTF_nome.setBounds(630, 230, 300, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Limpar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 470, 130, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(680, 470, 130, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(820, 470, 130, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setText("Alterar Administrador");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 0, 600, 90);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Usuário:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(510, 290, 100, 20);

        jTF_usuario.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTF_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_usuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        getContentPane().add(jTF_usuario);
        jTF_usuario.setBounds(630, 290, 300, 30);

        codigo.setEditable(false);
        codigo.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        getContentPane().add(codigo);
        codigo.setBounds(820, 180, 70, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Administrador Nº:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(590, 180, 217, 30);

        jTF_cod.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTF_cod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_cod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jTF_cod);
        jTF_cod.setBounds(730, 130, 70, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Insira o código:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(530, 130, 188, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("OK");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(810, 130, 80, 30);

        jTF_senha.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTF_senha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_senha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        getContentPane().add(jTF_senha);
        jTF_senha.setBounds(630, 350, 300, 30);

        jTF_senhaextra.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTF_senhaextra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_senhaextra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        getContentPane().add(jTF_senhaextra);
        jTF_senhaextra.setBounds(630, 410, 300, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cute-puppy-dog-pet-face-hand_1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 960, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String codigooo = codigo.getText();
        String nome = jTF_nome.getText();
        String usuario = jTF_usuario.getText();
        String senha = jTF_senha.getText();
        String senhaextra = jTF_senhaextra.getText();

        if (nome.equalsIgnoreCase("") || usuario.equalsIgnoreCase("") || senha.equalsIgnoreCase("") || senhaextra.equalsIgnoreCase("")) {
            
            JOptionPane.showMessageDialog(null,"Nenhum campo pode ficar vazio!!","Erro", JOptionPane.WARNING_MESSAGE);
            

        }
        else{
            Connection con = Conexao.AbrirConexao(); 
            AdministradorDAO sql = new AdministradorDAO(con);
            
            int cod = Integer.parseInt(codigooo);
            Administrador a = new Administrador();
            
            a.setCod(cod);
            a.setNome(nome);
            a.setUsuario(usuario);
            a.setSenha(senha);
            a.setSenhaextra(senhaextra);
            
            sql.Alterar_Administrador(a);
            
            Conexao.FecharConexao(con);
            
            jTF_nome.setText("");
            jTF_usuario.setText("");
            jTF_senha.setText("");
            jTF_senhaextra.setText("");
            codigo.setText("");
            
            
            JOptionPane.showMessageDialog(null,"Administrador alterado com sucesso", "sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTF_nome.setText("");
        jTF_senha.setText("");
        jTF_senhaextra.setText("");
        codigo.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String codigoo = jTF_cod.getText();
        Connection con = Conexao.AbrirConexao();
        AdministradorDAO sql = new AdministradorDAO(con);
        int cod = Integer.parseInt(codigoo);

        if (sql.Testar_Administrador(cod) == false) {
            JOptionPane.showMessageDialog(null,"Codigo não encontrado no banco",
                "Locadora", JOptionPane.ERROR_MESSAGE);
            Conexao.FecharConexao(con);
        }
        if (codigo.equals("")) {
            JOptionPane.showMessageDialog(null,"Digite um codigo para atualizar",
                "Locadora", JOptionPane.WARNING_MESSAGE);
        }

        codigo.setText("");
        jTF_nome.setText("");
        jTF_usuario.setText("");
        jTF_senha.setText("");
        jTF_senhaextra.setText("");
        
        InserirDados(cod);
        jTF_cod.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTF_cod;
    private javax.swing.JTextField jTF_nome;
    private javax.swing.JTextField jTF_senha;
    private javax.swing.JTextField jTF_senhaextra;
    private javax.swing.JTextField jTF_usuario;
    // End of variables declaration//GEN-END:variables
}
