/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Alterar;

import Visao.Cadastrar.*;
import DAO.Conexao;
import DAO.AnimalDAO;
import Modelo.Animal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Euxz
 */
public class AlterarAnimal extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarFuncionario
     */
    public AlterarAnimal() {
        initComponents();
        setSize(975, 575);
    }

    private void InserirDados(int cod){
        
        Connection con = Conexao.AbrirConexao();
        AnimalDAO sql = new AnimalDAO(con);
        List<Animal> lista = new ArrayList<>();
        lista = sql.CapturarAnimal(cod);
        
        for(Animal a : lista){
            codigo.setText(""+ a.getCod());
            jTF_nome.setText(a.getNome());
            jTF_tipo.setText(a.getTipo());
            jTF_raca.setText(a.getRaca());
            jTF_tamanho.setText(""+ a.getTamanho());
            jTF_peso.setText(""+ a.getPeso());
            jTF_idade.setText(""+ a.getIdade());
        }
        Conexao.FecharConexao(con);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF_peso = new javax.swing.JTextField();
        jTF_idade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTF_tipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTF_nome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTF_tamanho = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTF_raca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTF_cod = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Peso:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 330, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Idade:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 370, 80, 20);

        jTF_peso.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTF_peso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_peso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        getContentPane().add(jTF_peso);
        jTF_peso.setBounds(120, 330, 220, 21);

        jTF_idade.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTF_idade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_idade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        getContentPane().add(jTF_idade);
        jTF_idade.setBounds(120, 370, 220, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Limpar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 400, 120, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 400, 120, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 400, 120, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Browallia New", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alterar Animal");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, -10, 220, 80);

        jTF_tipo.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTF_tipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_tipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jTF_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_tipoActionPerformed(evt);
            }
        });
        getContentPane().add(jTF_tipo);
        jTF_tipo.setBounds(120, 210, 220, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 200, 45, 30);

        jTF_nome.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTF_nome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        getContentPane().add(jTF_nome);
        jTF_nome.setBounds(120, 170, 220, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nome:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 170, 60, 20);

        jTF_tamanho.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTF_tamanho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_tamanho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        getContentPane().add(jTF_tamanho);
        jTF_tamanho.setBounds(120, 290, 220, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tamanho:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 290, 92, 20);

        jTF_raca.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTF_raca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_raca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        getContentPane().add(jTF_raca);
        jTF_raca.setBounds(120, 250, 220, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Raça:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 240, 52, 30);

        jTF_cod.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTF_cod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_cod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jTF_cod);
        jTF_cod.setBounds(160, 70, 70, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Insira o código:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 70, 141, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Animal Nº:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 120, 98, 30);

        codigo.setEditable(false);
        codigo.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        getContentPane().add(codigo);
        codigo.setBounds(120, 130, 70, 20);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("OK");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 70, 60, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Dog-front-view-pet_1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -40, 960, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String codigooo = codigo.getText();
        String nome = jTF_nome.getText();
        String tipo = jTF_tipo.getText();
        String raca = jTF_raca.getText();
        String tamanho = jTF_tamanho.getText();
        String peso = jTF_peso.getText();
        String idade = jTF_idade.getText();
        
        if (nome.equalsIgnoreCase("") || tipo.equalsIgnoreCase("") || raca.equalsIgnoreCase("") || tamanho.equalsIgnoreCase("") || peso.equalsIgnoreCase("") || idade.equalsIgnoreCase("")) {
            
            JOptionPane.showMessageDialog(null,"Nenhum campo pode ficar vazio!!","Erro", JOptionPane.WARNING_MESSAGE);
            

        }
        else{
            Connection con = Conexao.AbrirConexao(); 
            AnimalDAO sql = new AnimalDAO(con);
            Animal a = new Animal();
            
            int cod = Integer.parseInt(codigooo);
            double tamanhoo = Double.parseDouble(tamanho);
            double pesoo = Double.parseDouble(peso);
            int idadee = Integer.parseInt(idade);
            
            a.setCod(cod);
            a.setNome(nome);
            a.setTipo(tipo);
            a.setRaca(raca);
            a.setTamanho(tamanhoo);
            a.setPeso(pesoo);
            a.setIdade(idadee);
            
            sql.Alterar_Animal(a);
            
            Conexao.FecharConexao(con);
            
            jTF_nome.setText("");
            jTF_tipo.setText("");
            jTF_raca.setText("");
            jTF_tamanho.setText("");
            jTF_peso.setText("");
            jTF_idade.setText("");
            jTF_idade.setText("");
            codigo.setText("");
            
            JOptionPane.showMessageDialog(null,"Animal alterado com sucesso", "sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTF_nome.setText("");
        jTF_tipo.setText("");
        jTF_raca.setText("");
        jTF_tamanho.setText("");
        jTF_peso.setText("");
        jTF_idade.setText("");
        codigo.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String codigoo = jTF_cod.getText();
        Connection con = Conexao.AbrirConexao();
        AnimalDAO sql = new AnimalDAO(con);
        int cod = Integer.parseInt(codigoo);

        if (sql.Testar_Animal(cod) == false) {
            JOptionPane.showMessageDialog(null,"Codigo não encontrado no banco",
                "Locadora", JOptionPane.ERROR_MESSAGE);
            Conexao.FecharConexao(con);
        }
        if (codigo.equals("")) {
            JOptionPane.showMessageDialog(null,"Digite um codigo para atualizar",
                "Locadora", JOptionPane.WARNING_MESSAGE);
        }

        codigo.setText("");
        jTF_nome.setText("");
        jTF_tipo.setText("");
        jTF_raca.setText("");
        jTF_tamanho.setText("");
        jTF_peso.setText("");
        jTF_idade.setText("");

        InserirDados(cod);
        jTF_cod.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTF_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_tipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTF_cod;
    private javax.swing.JTextField jTF_idade;
    private javax.swing.JTextField jTF_nome;
    private javax.swing.JTextField jTF_peso;
    private javax.swing.JTextField jTF_raca;
    private javax.swing.JTextField jTF_tamanho;
    private javax.swing.JTextField jTF_tipo;
    // End of variables declaration//GEN-END:variables
}
